### 01. NumPy
- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리의 근본!!

### 1-1. ndarray
- NumPy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [2]:
import numpy as np

In [ ]:
# ndarray의 생성
a = np.array([[1,2,3],[4,5,6]]) # 2행, 3열
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수
print(f"배열의 차원: {a.ndim}")

# 데이터 타입
print(f"배열의 데이터타입: {a.dtype}")
print(f"배열의 데이터타입: {b.dtype}")

# 형변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터타입: {new_a.dtype}")

배열의 구조: (2, 3)
배열의 차원: 2
배열의 데이터타입: int64
배열의 데이터타입: float64
수정한 배열의 데이터타입: float64


In [ ]:
# 3차원 행렬
a = np.array([[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (3, 2, 3)
배열의 차원: 3


In [20]:
# 4차원 행렬
a = np.array([[[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]]],
                
                [[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (2, 3, 2, 3)
배열의 차원: 4


In [18]:
# 만들 수 없는 배열
# 내부 배열의 구조가 같아야 함
a = np.array([[1],[2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 1-2. 배열 초기화 

In [25]:
# 모든 요소가 0인 배열 생성
np.zeros((3,4)) # 2차원
np.zeros((2,3,4), dtype=np.int64) # 3차원

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [26]:
# 모든 요소가 1인 배열 생성
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2,3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [28]:
# 주어진 값으로 채운 배열
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 단위 행렬
np.eye(3,3) # 정사각형
np.eye(3,5) # 직각사각형
np.eye(3,5,1) # 3번째 인자를 입력 → 1이 오른쪽으로 이동 / 음수를 입력하면 반대로 이동

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
### 1-3. 범위 기반 배열 생성

In [38]:
# arange : range()와 유사한 기능을 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2) # 간격 지정

array([0, 2, 4, 6, 8])

In [41]:
# linspace : 시작 ~ 끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함
np.linspace(10, 100, 10)
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [44]:
# reshape : 배열의 구조를 재배치
# np.linspace(1, 10, 10).reshape((2,3)) # 원소의 개수가 같아야 한다.
np.linspace(5, 100, 20).reshape((4,5))

array([[  5.,  10.,  15.,  20.,  25.],
       [ 30.,  35.,  40.,  45.,  50.],
       [ 55.,  60.,  65.,  70.,  75.],
       [ 80.,  85.,  90.,  95., 100.]])

### 1-4. 랜덤 배열 생성

In [45]:
# random.rand(m, n) 0~1 사이의 난수로 초기화
np.random.rand(2,3)

array([[0.36431563, 0.18327334, 0.00625487],
       [0.29111952, 0.6674093 , 0.23828754]])

In [ ]:
# random.randn(m, n) : 표준정규분포를 따르는 난수로 초기화
# 표준정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(4,5)

# random.normal(평균, 분산, 사이즈)
# 정규분포
np.random.normal(10,20, (2,4))

array([[-1.56608544, -0.26335493, -1.13575782, -0.97180762,  0.38931627],
       [ 1.08345269,  0.49685678, -0.35927774, -0.16021959, -0.99602417],
       [ 0.46997017,  0.10828818, -0.70024551, -0.30105073, -1.33688689],
       [ 0.09207837,  0.08643128,  0.19249964,  0.13613595, -1.01399956]])

In [48]:
# random.randint(low, high, (size))
print(np.random.randint(0, 101, (3,3)))

[[27 59 13]
 [97 88 72]
 [ 4 42 24]]


In [ ]:
# random.seed() : 난수 생성시 시작값 제공
np.random.seed(42) # seed를 고정하면 고정된 값만 나온다.
print(np.random.rand(2,3))
print(np.random.randn(2,2))
print(np.random.randint(0, 101, (3,3)))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]]
[[63 59 20]
 [32 75 57]
 [21 88 48]]


In [66]:
# RNG(Random Number Generator)
# 최근 파이썬 사용에서 권장되는 방식

from numpy.random import default_rng
rng = default_rng(seed=42)
rng2 = default_rng(seed=10)
rng3 = default_rng()

print(rng.random((3,2))) # 0~1 사이의 난수
print(rng2.normal(0, 1, (4,5))) # 정규분포
print(rng3.integers(0, 100, (2,2))) # 정수 난수
print(rng.uniform(0, 100, (4,4))) # 균등 분포

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[-1.10333845 -0.72502464 -0.78180526  0.26697586 -0.24858073]
 [ 0.12648305  0.84304257  0.85793655  0.47518364 -0.4507686 ]
 [-0.75493228 -0.81481411 -0.34385486 -0.05138009 -0.97227368]
 [-1.13448753  0.30570522 -1.85168503 -0.17705351  0.42582567]]
[[48 61]
 [72 14]]
[[76.1139702  78.60643053 12.81136327 45.03859379]
 [37.07980242 92.67649888 64.38651201 82.27616133]
 [44.34141988 22.72387218 55.4584787   6.38172561]
 [82.7631172  63.16643991 75.80877401 35.45259681]]


In [ ]:
# 실습1. 배열 초기화 및 생성(1)
# 문제1. 0으로채워진크기(3,4)배열을생성한후,모든값을5로채우는새로운배열을만드세요.
a1 = np.zeros((3,4))
a1_2 = np.full((3,4), 5)
print(f"문제1", a1, a1_2, sep="\n")

# 문제2. 0부터 20까지 2씩 증가하는 1차원 배열을 생성하세요.
a2 = np.arange(0, 21, 2)
print(f"\n문제2", a2)

# 문제3. 0~1 사이의 실수 난수를 가지는 (2, 3) 크기의 배열을 생성하세요.
a3 = np.random.rand(2,3)
print(f"\n문제3",a3)

# 문제4. 평균이 100, 표준편차가 20인 정규분포 난수 6개를 생성하세요.
a4 = np.random.normal(100, 20, 6)
print(f"\n문제4", a4)


문제1
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

문제2 [ 0  2  4  6  8 10 12 14 16 18 20]

문제3 [[0.84028015 0.1830669  0.70843822]
 [0.03717469 0.68326954 0.01866372]]

문제4 [84.22793454 80.63503424 86.91560321 74.50068588 55.06959509 93.67618045]


In [ ]:
# 문제5. 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환하세요.
a5 = np.arange(1, 21).reshape(4, 5)
print(f"\n문제5", a5)

# 문제6. 0부터1까지균등간격으로나눈12개의값을가지는배열을생성하고,이를(3,4)크기로변 환하세요.
a6 = np.linspace(0, 1, 12).reshape(3, 4)
print(f"\n문제6", a6)

# 문제7. 0~99 사이의 난수로 이루어진 (10, 10) 배열을 생성한 뒤, np.eye()로 만든 단위 행렬을 더 하여 대각선 요소가 1씩 증가된 배열을 만드세요.
a7 = np.random.randint(0, 100, (10, 10))
a7_eye = np.eye(10)
print(f"\n문제7", a7 + a7_eye) # 행렬의 덧셈

# 문제8. 0~9 사이의 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요.
a8 = np.random.randint(0, 10, (2, 3, 4))
print(f"\n문제8", a8)



문제5 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

문제6 [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]

문제7 [[43. 71. 52. 91. 34. 22. 86. 52. 31.  3.]
 [ 0. 95. 10. 37. 84.  0.  9. 62. 74.  7.]
 [10. 72.  7. 29. 76. 28. 75. 54. 50. 72.]
 [14. 94. 33. 19. 51. 65. 92. 34. 31. 41.]
 [59. 90.  2. 33. 91. 92. 15. 36.  0. 54.]
 [33. 18. 22. 46.  3. 60. 68. 72. 83. 19.]
 [11. 17.  7.  7.  3. 69. 91. 22. 54. 96.]
 [53. 65. 80. 90. 96. 14. 98. 84. 57. 83.]
 [ 6. 41. 54. 35. 39. 17. 40. 54.  8. 31.]
 [ 2. 58. 33. 53. 66. 78. 72. 87. 22. 62.]]

문제8 [[[3 3 0 1]
  [4 1 8 6]
  [3 4 1 2]]

 [[3 4 8 5]
  [1 5 0 8]
  [4 2 3 9]]]


### 1-5. 인덱싱과 슬라이싱
- 다차원 배열을 다루는 편의 기능 제공
- python의 시퀀스보다 빠름

In [14]:
# 인덱싱
a = np.array([10, 20, 30, 40, 50])
print(a[2])
print(a[-1])

30
50


In [ ]:
# 다차원 인덱싱
# 파이썬 리스트
matrix = [[1,2,4], [4,5,6]] # 2*3차원
print("파이썬 인덱싱:", matrix[1][1])

# NumPy 배열
a2 = np.array([[1,2,4], [4,5,6]])
print(a2.shape)
print("numpy 인덱싱:", a2[1,2]) # 2차원 먼저 읽어줌

파이썬 인덱싱: 5
(2, 3)
numpy 인덱싱: 6


In [21]:
# 3차원 배열 인덱싱
a3 = np.arange(24).reshape(2,3,4)
print(a3)
print(a3.shape)
print("17", a3[1,1,1]) # 17읽기
print("11", a3[0,2,3]) # 11읽기
print("23", a3[1,2,3]) # 23읽기

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
17 17
11 11
23 23


In [ ]:
# 슬라이실
# arr[행_슬라이스, 열_슬라이스]
# arr[..., 4차원슬라이스, 3차원슬라이스, 2차원슬라이스, 1차원슬라이스]
a1 = np.array([10,20,30,40,50])

print(a1[1:3])
print(a1[2:])
print(a1[:2])
print(a1[:])
print(a1[::2])
print(a1[::-1])


[20 30]
[30 40 50]
[10 20]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [ ]:
# 파이썬 리스트와의 차이
# 파이썬 라스트
# 원본은 변경되지 않음
py_list = [10,20,30,40,50]
sliced = py_list[1:4]
sliced[1] = 100
print("py원본:", py_list)
print("py슬라이싱:", sliced)
print()

# numpy 배열
# 원본도 같이 변경됨
a1 = np.array([10,20,30,40,50])
a1_sliced = a1[1:4]
a1_sliced[1] = 100
print("numpy원본:", a1)
print("numpy슬라이싱:", a1_sliced)

py원본: [10, 20, 30, 40, 50]
py슬라이싱: [20, 100, 40]

numpy원본: [ 10  20 100  40  50]
numpy슬라이싱: [ 20 100  40]


In [65]:
# 2차원 배열 슬라이싱
a2 = np.arange(1, 21).reshape(4, 5)
print("원본", a2)
print()

# 행 슬라이싱(2차원 슬라이싱)
print("1.",a2[0, :]) # 2차원 기준 0번째 원소, 1차원자리 다 불러와!
print("2.",a2[0]) # 위에랑 같음
print("3.",a2[1])
print("4.",a2[1:3]) # 인덱싱 2,3 불러옴


원본 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

1. [1 2 3 4 5]
2. [1 2 3 4 5]
3. [ 6  7  8  9 10]
4. [[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
# 열 슬라이싱(1차원 슬라이싱)
# 하나만 자르면 1차원으로 나눠지고, 여러개 자르면 차원을 유지함.
print(a2[:, 2]) # 모든 행에 2번째 열을 각각 불러옴
print(a2[:, -1]) 
print(a2[:, 1:3]) # 모든 행에 1,2번재 열을 각각 불러옴

[ 3  8 13 18]
[ 5 10 15 20]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


In [44]:
# 행과 열 슬라이싱
print(a2)
print(a2[1:3, 2:4])
print(a2[2:, 3:])
print(a2[::2, ::2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9]
 [13 14]]
[[14 15]
 [19 20]]
[[ 1  3  5]
 [11 13 15]]


In [46]:
# 3차원 슬라이싱
a3 = np.arange(36).reshape(3, 3, 4)
print(a3)
print(a3[1, 1, 1:3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
[17 18]


In [50]:
# 얕은 복사 : 복사본이 원본과 메모리를 공유 → 변경사항이 서로에세 영향을 줌
a1 = np.array([1,2,3])
a1_copied = a1.view()
a1_copied[1] = 10
print("원본", a1)
print("얕은 복사본", a1_copied)
print()

# 깊은 복사 : 복사본이 원본과 독립적으로 복사됨 → 서로 영향을 주지X
a2 = np.array([1,2,3])
a2_copied = a2.copy()
a2_copied[1] = 10
print("원본", a2)
print("깊은 복사본", a2_copied)

원본 [ 1 10  3]
얕은 복사본 [ 1 10  3]

원본 [1 2 3]
깊은 복사본 [ 1 10  3]


In [ ]:
# Fancy indexing
# 정수 배열을 사용하여 여러 인덱스로 여러 요소를 한번에 선택
af = np.arange(1,21)
# print(af)
# print(af[[4,7,11]]) # 여러요소를 한번에 선택할 때 정수배열을 선택하고,, 그래서 괄호가 2개

af2 = np.arange(1,21).reshape(4,5)
print(af2)
print(af2[[1,3], [2,4]]) # (1,2) (3,4)가 선택됨

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 8 20]


In [57]:
# Boolean indexing
ab = np.linspace(10,100,10)
print(ab)
print(ab[ab > 40])

# Boolean masking
ab2 = np.arange(0,21)
print(ab2)
mask = ab2 % 2 == 0
print(mask)
print(ab2[mask]) # True면 반환하고, False면 반환 안됨

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 50.  60.  70.  80.  90. 100.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [90]:
# 실습2. 인덱싱과 슬라이싱(2)
# 문제1. 다음 배열에서 2, 4, 6번째 요소를 Fancy Indexing으로 선택하세요. 
arr=np.arange(10,30,2)
print("1.원본 배열:\n", arr)
print("\n",arr[[1, 3, 5]])
print()

# 문제2. 3x3 배열에서 왼쪽 위 → 오른쪽 아래 대각선의 요소만 인덱싱으로 추출하세요.
arr=np.arange(1,10).reshape(3,3)
print("2.원본 배열:\n", arr)
print("\n",arr[[0, 1, 2], [0, 1, 2]]) # (0,0) (1,1) (2,2) 출력
print()

# 문제3. 3x4 배열에서 마지막 열만 선택해 모두 -1로 변경하세요.
arr=np.arange(1,13).reshape(3,4)
print("3.원본 배열:\n", arr)
arr[:,-1] = -1 
print("\n", arr)
print()

# 문제4. 4x4 배열에서 행을 역순, 열을 역순으로 각각 슬라이싱해 출력하세요.
arr=np.arange(1,17).reshape(4,4)
print("4.원본 배열:\n", arr)
print("행 역순:\n", arr[::-1, :])
print("열 역순:\n", arr[:, ::-1])
print()



1.원본 배열:
 [10 12 14 16 18 20 22 24 26 28]

 [12 16 20]

2.원본 배열:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [1 5 9]

3.원본 배열:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]]

4.원본 배열:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
행 역순:
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
열 역순:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]



In [99]:

# 문제5. 4x5 배열에서 가운데 2x3 부분을 슬라이싱한 뒤 copy()를 이용해 독립 배열을 만드세요.
arr = np.arange(1, 21).reshape(4, 5)
print("5.원본 배열:\n", arr)
arr_copy = arr[1:3, 1:4].copy()
print("\n",arr)
print()

# 문제6. 3x4배열에서 짝수이면서 10이상인 값만 선택하세요.
arr = np.array([[ 4, 9, 12, 7], [10, 15, 18, 3], [ 2, 14, 6, 20]])
print("6.원본 배열:\n", arr)
mask = (arr % 2 == 0) & (arr >= 10)
selected = arr[mask]
print("\n짝수이면서 10이상인 값:", selected)
print()


# 문제7. 5x5 배열에서 2, 4번째 행을 선택하고, 선택된 행에서 열 순서를 [4, 0, 2]로 재배치하세요.
arr = np.arange(1, 26).reshape(5, 5)
print("7.원본 배열:\n", arr)
result = arr[[1,3]]
print("\n",result)

# 방법1.
# answer = []
# for i in result:
    # answer.append([i[4], i[0], i[2]])
# print(np.array(answer))

# 방법2.
result[:, [4,0,2]]
print()

5.원본 배열:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

6.원본 배열:
 [[ 4  9 12  7]
 [10 15 18  3]
 [ 2 14  6 20]]

짝수이면서 10이상인 값: [12 10 18 14 20]

7.원본 배열:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 [[ 6  7  8  9 10]
 [16 17 18 19 20]]



In [97]:
# 문제8. 5x3 배열에서 각 행의 첫 번째 값이 50 이상인 행만 Boolean Indexing으로 선택하세요.
arr = np.array([[10, 20, 30], [55, 65, 75], [40, 45, 50], [70, 80, 90], [15, 25, 35]]) 
print("8.원본 배열:\n", arr)
mask = arr[:,0] >= 50
print("\n",arr[mask])
print()

# 문제9. 4x4 배열에서 (0,1), (1,3), (2,0), (3,2) 위치의 요소를 한 번에 선택하세요.
arr=np.arange(1,17).reshape(4,4)
print("9.원본 배열:\n", arr)
selected = arr[[0, 1, 2, 3], [1, 3, 0, 2]]
print("\n",selected)
print()

# 문제10. 3차원배열(2,3,4)에서 모든 블록에서 두 번째 열만 추출해 새로운 2차원 배열(2,3)을 만드세요.
arr3d=np.arange(24).reshape(2,3,4)
print("10.원본 배열:\n", arr3d)
result = arr3d[:, :, 1]
print("\n두 번째 열만 추출한 결과:\n", result)



8.원본 배열:
 [[10 20 30]
 [55 65 75]
 [40 45 50]
 [70 80 90]
 [15 25 35]]

 [[55 65 75]
 [70 80 90]]

9.원본 배열:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 [ 2  8  9 15]

10.원본 배열:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

두 번째 열만 추출한 결과:
 [[ 1  5  9]
 [13 17 21]]


In [105]:
# 실습3. NumPy 종합 연습(1)
# 문제1. 0부터24까지정수를가진배열을만들고,(5,5)배열로변환한뒤가운데행(3번째행)과가운데 열(3번째 열)을 각각 1차원 배열로 출력하세요.
a1 = np.arange(25).reshape(5, 5)
print("원본 배열:\n", a1)

middle_row = a1[2, :]
middle_col = a1[:, 2]

print("\n가운데 행(3번째 행):", middle_row)
print("가운데 열(3번째 열):", middle_col)


원본 배열:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

가운데 행(3번째 행): [10 11 12 13 14]
가운데 열(3번째 열): [ 2  7 12 17 22]


In [106]:
# 문제2. 0~99 난수로 이루어진 (10, 10) 배열을 생성하고, 짝수 인덱스의 행만 선택하여 출력하세요.

# 0~99 난수로 (10, 10) 배열 생성
a2 = np.random.randint(0, 100, (10, 10))
print("원본 배열:\n", a2)

# 짝수 인덱스의 행만 선택 (0, 2, 4, 6, 8)
even_rows = a2[::2, :]
print("\n짝수 인덱스의 행만:\n", even_rows)

원본 배열:
 [[ 1 76 51 86 20 64 96 69 39  3]
 [10 35 45 52 74  1 76 59 72 40]
 [70 40 49 22 81 37 39 12 73 32]
 [44 83 42 31 25 29 73 60 25 97]
 [46 78 89 57 14 47 60 49 77 77]
 [45 98  1 25 49 12 50 57 18 13]
 [74 36  8 51 31 92 66 97 91 70]
 [23  0 91 94 17 64 39  1 22 98]
 [79 99 28 39 90 70 38 62 59  0]
 [70 41 76 94 45 41 14 44  8 60]]

짝수 인덱스의 행만:
 [[ 1 76 51 86 20 64 96 69 39  3]
 [70 40 49 22 81 37 39 12 73 32]
 [46 78 89 57 14 47 60 49 77 77]
 [74 36  8 51 31 92 66 97 91 70]
 [79 99 28 39 90 70 38 62 59  0]]


In [107]:
# 문제3. 0부터49까지정수를가진배열을(5,10)배열로변환한후,2행3열부터4행7열까지의부 분 배열을 추출하세요.

a3 = np.arange(50).reshape(5, 10)
print("원본 배열:\n", a3)

# 부분 배열 슬라이싱
sub_arr = a3[2:5, 3:8]
print("\n2행 3열부터 4행 7열까지의 부분 배열:\n", sub_arr)


원본 배열:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

2행 3열부터 4행 7열까지의 부분 배열:
 [[23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]]


In [113]:
# 문제4. 0~9 난수로 이루어진 (4, 4) 배열을 생성하고, 각각 인덱싱으로 추출해 출력하세요.(for 이용)
#  주대각선요소(왼쪽위→오른쪽아래) , 부대각선요소(오른쪽위→왼쪽아래)
a4 = np.random.randint(0, 10, (4, 4))
print("원본 배열:\n", a4)
print("주대각선 (Fancy Indexing):", a4[[0, 1, 2, 3], [0, 1, 2, 3]])
print("부대각선 (Fancy Indexing):", a4[[0, 1, 2, 3], [3, 2, 1, 0]])

print("주대각선 (for문):", end=" ")
for i in range(4):
    print(a4[i, i], end=" ")
print()

print("부대각선 (for문):", end=" ")
for i in range(4):
    print(a4[i, 3-i], end=" ")
print()



원본 배열:
 [[2 3 9 7]
 [6 2 5 5]
 [5 7 7 5]
 [3 4 5 2]]
주대각선 (Fancy Indexing): [2 2 7 2]
부대각선 (Fancy Indexing): [7 5 7 3]
주대각선 (for문): 2 2 7 2 
부대각선 (for문): 7 5 7 3 


In [114]:
# 문제5. 0~9난수로이루어진(3,4,5)3차원배열을생성하고,두번째층에서첫번째행과마지막 열의 값을 출력하세요.
a5 = np.random.randint(0,10,(3,4,5))
print("원본 배열:\n", a5)
print("\n두 번째 층 첫 번째 행:", a5[1, 0, :])
print("두 번째 층 마지막 열:", a5[1, :, -1])


원본 배열:
 [[[1 3 7 6 6]
  [7 9 8 6 3]
  [3 2 2 7 6]
  [6 5 8 7 3]]

 [[8 2 0 1 6]
  [2 2 6 9 5]
  [4 4 9 7 1]
  [6 6 2 8 3]]

 [[6 5 4 4 3]
  [3 1 5 5 7]
  [6 9 7 1 9]
  [5 8 7 0 2]]]

두 번째 층 첫 번째 행: [8 2 0 1 6]
두 번째 층 마지막 열: [6 5 1 3]


In [115]:
# 문제6. 35부터 74까지의 순차적인 수로 이루어진 1차원 배열을 만들고 10x4 행렬로 변환 후 출력해 주세요.

arr = np.arange(35, 75)   # 35부터 74까지 (총 40개)
arr_2d = arr.reshape(10, 4)
print("6. 10x4 배열:\n", arr_2d)


# 문제7. 6번에서 만든 배열을 맨 끝의 행부터 역순으로 출력해주세요.
print("\n7. 행 역순 출력:\n", arr_2d[::-1, :])



6. 10x4 배열:
 [[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]

7. 행 역순 출력:
 [[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]


In [117]:
# 문제8. 6번에서만든배열중두번째행부터마지막직전행까지,세번째열부터마지막열까지슬라 이싱해서 출력해주세요.

arr = np.arange(35, 75).reshape(10, 4)
sub_arr = arr[1:9, 2:]
print("8. 슬라이싱 결과:\n", sub_arr)

# 문제9. 1부터 50까지의 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택하여 출력하는 코드를 작성하세요.

rand_arr = np.random.randint(1, 51, (5, 6))
print("9. 원본 배열:\n", rand_arr)

even_arr = rand_arr[rand_arr % 2 == 0]
print("\n 배열 내 짝수만:\n", even_arr)


8. 슬라이싱 결과:
 [[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]
9. 원본 배열:
 [[27  1  1 28 11 50]
 [13 37 39 13 36 36]
 [42 47 29 40 13 48]
 [28 20  6 39 17 33]
 [18  1 37 41 10 21]]

 배열 내 짝수만:
 [28 50 36 36 42 40 48 28 20  6 18 10]


In [118]:
# 문제10. 0부터 99까지의 정수로 이루어진 (10, 10) 배열을 생성한 후, [1, 3, 5]번째 행과 [2, 4, 6]번째 열의 교차하는 원소들만 선택하여 출력하세요.

arr = np.arange(100).reshape(10, 10)
print("10. 원본 배열:\n", arr)

# [1, 3, 5]번째 행, [2, 4, 6]번째 열의 교차 원소
rows = [1, 3, 5]
cols = [2, 4, 6]
result = arr[np.ix_(rows, cols)]  # ix_를 쓰면 교차하는 원소의 2차원 배열 반환

print("\n10. 교차하는 원소들:\n", result)



# 문제11.  0~9난수로이루어진1차원배열(길이15)을생성하고, 짝수 인덱스 위치에 있는 값들 중에서 5 이상인 값만 선택해 출력하세요.

arr = np.random.randint(0, 10, 15)
print("11. 원본 배열:", arr)

even_index_values = arr[::2]          # 짝수 인덱스 위치의 값들
selected = even_index_values[even_index_values >= 5]  # 그 중 5 이상만

print("\n11. 짝수 인덱스 중 5 이상:", selected)



10. 원본 배열:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

10. 교차하는 원소들:
 [[12 14 16]
 [32 34 36]
 [52 54 56]]
11. 원본 배열: [2 2 8 9 3 7 0 7 5 6 6 3 0 6 4]

11. 짝수 인덱스 중 5 이상: [8 5 6]
