### 01. NumPy
- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리의 근본!!

### 1-1. ndarray
- NumPy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [21]:
import numpy as np

In [ ]:
# ndarray의 생성
a = np.array([[1,2,3],[4,5,6]]) # 2행, 3열
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수
print(f"배열의 차원: {a.ndim}")

# 데이터 타입
print(f"배열의 데이터타입: {a.dtype}")
print(f"배열의 데이터타입: {b.dtype}")

# 형변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터타입: {new_a.dtype}")

배열의 구조: (2, 3)
배열의 차원: 2
배열의 데이터타입: int64
배열의 데이터타입: float64
수정한 배열의 데이터타입: float64


In [ ]:
# 3차원 행렬
a = np.array([[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (3, 2, 3)
배열의 차원: 3


In [20]:
# 4차원 행렬
a = np.array([[[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]]],
                
                [[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (2, 3, 2, 3)
배열의 차원: 4


In [18]:
# 만들 수 없는 배열
# 내부 배열의 구조가 같아야 함
a = np.array([[1],[2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 1-2. 배열 초기화 

In [25]:
# 모든 요소가 0인 배열 생성
np.zeros((3,4)) # 2차원
np.zeros((2,3,4), dtype=np.int64) # 3차원

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [26]:
# 모든 요소가 1인 배열 생성
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2,3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [28]:
# 주어진 값으로 채운 배열
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 단위 행렬
np.eye(3,3) # 정사각형
np.eye(3,5) # 직각사각형
np.eye(3,5,1) # 3번째 인자를 입력 → 1이 오른쪽으로 이동 / 음수를 입력하면 반대로 이동

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
### 1-3. 범위 기반 배열 생성

In [38]:
# arange : range()와 유사한 기능을 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2) # 간격 지정

array([0, 2, 4, 6, 8])

In [41]:
# linspace : 시작 ~ 끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함
np.linspace(10, 100, 10)
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [44]:
# reshape : 배열의 구조를 재배치
# np.linspace(1, 10, 10).reshape((2,3)) # 원소의 개수가 같아야 한다.
np.linspace(5, 100, 20).reshape((4,5))

array([[  5.,  10.,  15.,  20.,  25.],
       [ 30.,  35.,  40.,  45.,  50.],
       [ 55.,  60.,  65.,  70.,  75.],
       [ 80.,  85.,  90.,  95., 100.]])

### 1-4. 랜덤 배열 생성

In [45]:
# random.rand(m, n) 0~1 사이의 난수로 초기화
np.random.rand(2,3)

array([[0.36431563, 0.18327334, 0.00625487],
       [0.29111952, 0.6674093 , 0.23828754]])

In [46]:
# random.randn(m, n) : 표준정규분포를 따르는 난수로 초기화
# 표준정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(4,5)

array([[-1.56608544, -0.26335493, -1.13575782, -0.97180762,  0.38931627],
       [ 1.08345269,  0.49685678, -0.35927774, -0.16021959, -0.99602417],
       [ 0.46997017,  0.10828818, -0.70024551, -0.30105073, -1.33688689],
       [ 0.09207837,  0.08643128,  0.19249964,  0.13613595, -1.01399956]])

In [48]:
# random.randint(low, high, (size))
print(np.random.randint(0, 101, (3,3)))

[[27 59 13]
 [97 88 72]
 [ 4 42 24]]


In [ ]:
# random.seed() : 난수 생성시 시작값 제공
np.random.seed(42) # seed를 고정하면 고정된 값만 나온다.
print(np.random.rand(2,3))
print(np.random.randn(2,2))
print(np.random.randint(0, 101, (3,3)))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]]
[[63 59 20]
 [32 75 57]
 [21 88 48]]


In [66]:
# RNG(Random Number Generator)
# 최근 파이썬 사용에서 권장되는 방식

from numpy.random import default_rng
rng = default_rng(seed=42)
rng2 = default_rng(seed=10)
rng3 = default_rng()

print(rng.random((3,2))) # 0~1 사이의 난수
print(rng2.normal(0, 1, (4,5))) # 정규분포
print(rng3.integers(0, 100, (2,2))) # 정수 난수
print(rng.uniform(0, 100, (4,4))) # 균등 분포

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[-1.10333845 -0.72502464 -0.78180526  0.26697586 -0.24858073]
 [ 0.12648305  0.84304257  0.85793655  0.47518364 -0.4507686 ]
 [-0.75493228 -0.81481411 -0.34385486 -0.05138009 -0.97227368]
 [-1.13448753  0.30570522 -1.85168503 -0.17705351  0.42582567]]
[[48 61]
 [72 14]]
[[76.1139702  78.60643053 12.81136327 45.03859379]
 [37.07980242 92.67649888 64.38651201 82.27616133]
 [44.34141988 22.72387218 55.4584787   6.38172561]
 [82.7631172  63.16643991 75.80877401 35.45259681]]


In [82]:
# 실습1. 배열 초기화 및 생성(1)
np.zeros((3,4)) 
print(f"문제1", np.full((3,4), 5))

print(f"문제2", np.arange(0, 20, 2))

print(f"문제3", np.random.rand(2,3))

print(f"문제4", np.random.normal(loc=100, scale=20, size=6))

print(f"문제5", np.arange(1, 21).reshape(4, 5))

print(f"문제6", np.linspace(0, 1, 12).reshape(3, 4))
      
arr = np.random.randint(0, 100, (10, 10))
eye = np.eye(10, dtype=int)
print(f"문제7", arr + eye)
      

print(f"문제8", np.random.randint(0, 10, (2, 3, 4)))








문제1 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
문제2 [ 0  2  4  6  8 10 12 14 16 18]
문제3 [[0.52083426 0.96117202 0.84453385]
 [0.74732011 0.53969213 0.58675117]]
문제4 [101.92832958 108.38204211  80.93944422  79.04258795  62.48646456
  72.66435722]
문제5 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
문제6 [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]
문제7 [[ 8 87 62 10 80  7 34 34 32  4]
 [40 28  6 72 71 11 33 32 47 22]
 [61 87 37 98 43 85 90 34 64 98]
 [46 77  2  1  4 89 13 26  8 78]
 [14 89 41 76 51 62 95 51 95  3]
 [93 22 14 42 28 36 12 31 70 58]
 [85 27 65 41 44 61 57  5 27 27]
 [43 83 29 61 74 91 88 62 96  0]
 [26 61 76  2 69 71 26  8 62 36]
 [96 50 43 23 78 58 31 95 87 52]]
문제8 [[[0 0 9 3]
  [6 1 2 0]
  [4 0 7 0]]

 [[0 1 1 5]
  [6 4 0 0]
  [2 1 4 9]]]
